# Generated by Django 4.1.2 on 2022-10-18 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='fecha',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
