# Generated by Django 4.1.2 on 2022-10-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='nro_pasaporte',
            field=models.IntegerField(default=0),
        ),
    ]
