# Generated by Django 4.1.2 on 2022-10-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_nro_pasaporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='nro_pasaporte',
        ),
    ]
